version: "3"

includes:
  dev:
    taskfile: Taskfile.dev.yml
    flatten: true
  docker:
    taskfile: Taskfile.docker.yml
    flatten: true
  debug:
    taskfile: Taskfile.debug.yml
    flatten: true
  deploy:
    taskfile: Taskfile.deploy.yml
    flatten: true

tasks:
  help:
    desc: this help
    cmds:
      - task -a
