version: "3.7"
services:
  bastion:
    image: paulstuart/dqlite-prod:xenial
    hostname: bastion
    restart: always
    #stdin_open: true
    tty: true
    entrypoint:
      - bash
    environment:
        DQLITED_CLUSTER: "dqlbox1:9181,dqlbox2:9182,dqlbox3:9183"
    volumes:
      - .:/host

  dqlbox1:
    image: paulstuart/dqlite-prod:xenial
    hostname: dqlbox1
    restart: always
    entrypoint:
      - ./dqlited
      - server
      - --id
      - "1"
      - --address
      - "dqlbox1:9181"
      - --cluster
      - "dqlbox1:9181,dqlbox2:9182,dqlbox3:9183"
    ports:
      - "4001:4001"
      - "9181:9181"
    environment:
        DQLITED_CLUSTER: "dqlbox1:9181,dqlbox2:9182,dqlbox3:9183"
    volumes:
      - .:/host

  dqlbox2:
    image: paulstuart/dqlite-prod:xenial
    hostname: dqlbox2
    restart: always
    entrypoint:
      - ./dqlited
      - server
      - --id
      - "2"
      - --address
      - "dqlbox2:9182"
      - --cluster
      - "dqlbox1:9181,dqlbox2:9182,dqlbox3:9183"
    depends_on:
      - dqlbox1
    ports:
      - "4002:4001"
      - "9182:9182"
    environment:
        DQLITED_CLUSTER: "dqlbox1:9181,dqlbox2:9182,dqlbox3:9183"
    volumes:
      - .:/host

  dqlbox3:
    image: paulstuart/dqlite-prod:xenial
    hostname: dqlbox3
    restart: always
    entrypoint:
      - ./dqlited
      - server
      - --id
      - "3"
      - --address
      - "dqlbox3:9183"
      - --cluster
      - "dqlbox1:9181,dqlbox2:9182,dqlbox3:9183"
    depends_on:
      - dqlbox1
    ports:
      - "4003:4001"
      - "9183:9183"
    environment:
        DQLITED_CLUSTER: "dqlbox1:9181,dqlbox2:9182,dqlbox3:9183"
    volumes:
      - .:/host


networks:
  default:
    name: dqlite-network
